name: Build NRO

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Rust toolchain
  uses: actions-rs/toolchain@v1
  with:
    profile: minimal
    toolchain: nightly
    target: aarch64-skyline-switch
    override: true

    - name: Install cargo-skyline
      run: cargo install cargo-skyline

    - name: Build NRO
      run: cargo skyline build

    - name: Upload NRO
      uses: actions/upload-artifact@v4
      with:
        name: double_damage.nro
        path: target/aarch64-skyline-switch/release/double_damage.nro
